services:
  grader-linux:
    build:
      context: .
      dockerfile: Dockerfile
    image: grader-linux-test:latest
    container_name: grader-linux-test
    working_dir: /workspace/backend
    volumes:
      - ./:/workspace
      - maven-cache:/var/maven/.m2
    stdin_open: true
    tty: true
    command: sleep infinity
    ports:
      - 8080:8080

volumes:
  maven-cache:
